home-assistant/wheels

- builder/pip.py
- builder/upload/rsync.py
- builder/utils.py
- setup.py
```
The timeout argument is passed to Popen.communicate(). If the timeout expires, the child process will be killed and waited for. The TimeoutExpired exception will be re-raised after the child process has terminated.
```
This block with qemu. I reimplement `run` but make sure we don't block until the pip job is killed
> Better timeout handling

- action.yml
That are more up to date and work with our new base images they do not include qemu anymore
> Fix qemu build

- builder/__main__.py
- builder/infra.py
- tests/test_infra.py
Update wheel builder to consider package constraints when skipping binaries.
The basic idea is to ensure that --skip-binary can reference packages that are not explicit requirements to always force grpc to be built from source.
Reviewer note: An alternative could be to add grpcio to be an explicit requirement for an integration (e.g. nest/pubsub/google, etc)
For https://github.com/home-assistant/core/issues/56669
> Update builder to consider package constraints when skipping binaries (grpc fix)

- requirements_build.txt
Reverts home-assistant/wheels#307
Reverting since it appears to break the build process from discussion in https://github.com/home-assistant/wheels/pull/311
e.g. https://github.com/home-assistant/wheels/runs/4764481586?check_suite_focus=true
```
error: Command "gcc -shared -Wl,--strip-all build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/numpy/core/src/umath/loops_unary_fp.dispatch.sse41.o .... -lnpymath -o build/lib.linux-x86_64-3.8/numpy/core/_multiarray_umath.cpython-38-i386-linux-gnu.so" failed with exit status 1
```
> Revert "Bump numpy from 1.21.2 to 1.22.0"

- builder/__main__.py
- builder/infra.py
- tests/test_infra.py
grpcio armv7 wheels are broken again, due to this behavior:
- First time a new grpc version exists, its built from source due to --skip_binary=grpc (after #311 and https://github.com/home-assistant/core/pull/63521). Great.
- Second time a build happens (for another package bump) grpc is in the index then grpc is removed from --skip_binary to get it to use an existing wheel, but then it uses the pypi wheel rather than the home assistant index wheel (https://github.com/pypa/pip/issues/4321). Bad!
To remedy, add a new flag --skip_exists that will remove the local grpc wheel when it already exists in the index before syncing.
This change refactors existing code in `check_available_binary` to take advantage of its existing test coverage, but it makes the change bigger than to needs to be. …
> Add command line flag to avoid overwriting grpc wheels

- builder/__main__.py
Stop replacing the original value of skip binary so that the local wheel removal logic still works.
Current bug is that the wheel removal logic still doesn't work when then wheel already exists because --skip_binary gets overwritten. Bug was introduced when merging --skip_existing and --skip_binary.
Issue https://github.com/home-assistant/core/issues/56669
> Don't replace original value of skip_binary

- requirements_cp310.txt
Reverts home-assistant/wheels#502
We need to revert this one for now, as it breaks our CI at this moment.
> Revert "Bump cmake from 3.22.2 to 3.25.2"

- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
Fix deprecated command `set-output` in workflows
> Fix deprecated command `set-output` in workflows

- action.yml
Fix use ${{ github.action_path }} to ${GITHUB_ACTION_PATH} with bash pattern matching {##*/}
Issue: https://github.com/actions/runner/issues/716
> Fix use ${{ github.action_path }} to ${GITHUB_ACTION_PATH} with bash

- requirements.txt
Updates `pip` to 23.1
<https://pip.pypa.io/en/stable/news/#v23-1>
> Update pip to 23.1

- requirements_cp311.txt
Originally added in #448
Seems no longer needed, and we can use the (newer) version provided by Alpine instead. Going to remove it for ABI cp311 only.
This gives us the opportunity to test building all wheels, without harming/touching our current production.
CI: Is expected to fail (chicken-egg problem, as we don't have all images build on the `dev` branch yet).
> Remove cmake from Python requirements

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- README.md
- requirements_cp310.txt
As we no longer use it / provided it.
> Drop Python 3.10 / cp310

- Dockerfile
- builder/infra.py
- builder/pip.py
Adjusts our Wheels builder to use the index instead of the find-links logic.
> Use pep 503 compatible wheels index for builds

- requirements_wheels_test.txt
SSIA
We've moved to faust-cchardet (for which we don't need to test wheels).
> Remove cchardet from tests, we don't use it anymore

- Dockerfile
This should work to get `numpy` build with Python 3.12.
A bit more involved than usual, but until https://github.com/scikit-build/ninja-python-distributions/issues/220 is resolved, `ninja` needs to be build from git directly unfortunately.
/CC @frenck
> Fix numpy install (3.12)

- Dockerfile
Now that https://github.com/scikit-build/ninja-python-distributions/issues/220 is fixed, we can remove the custom build steps for `numpy`.
Additionally, I have started building the 3.12 wheels over in the core repo and the numpy ones for musllinux are up on https://wheels.home-assistant.io/musllinux/. This brings to build times back down in the range of 1-5min per job.
_Verified that the publish job would success, so it's safe to start a new release after this one._
https://github.com/cdce8p/wheels/actions/runs/6463289052
/CC @frenck
> Cleanup numpy install

- README.md
- requirements_cp311.txt
We already use `1.26.0` for Python 3.12, start using it for 3.11 as well.
That's the same version that's pinned by core for both 3.11 and 3.12.
This further improves the build times. The previous version `1.24.2` wasn't cached for some 3.11 platforms.
https://wheels.home-assistant.io/musllinux/
Full run: https://github.com/cdce8p/wheels/actions/runs/6466414134
> Update numpy to 1.26.0

- .github/workflows/ci.yml
- requirements_wheels_test.txt
This PR adds all requirements from our base image to our Wheels builder as well:
Ref: <https://github.com/home-assistant/docker/blob/master/requirements.txt>
This ensures we always test against these, as they are not tested/triggered anywhere else. It helps working around chicken/egg problems and ensure these can be build (as Core doesn't run it).
> Add requirements from base image to wheels test file

- builder/wheel.py
Noticed as the CI was failing here: <https://github.com/home-assistant/wheels/actions/runs/7420881519/job/20193096639>
> Add Alpine 3.19 platform to the Wheels builder

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- requirements_cp311.txt
Noticed we are still building the Python 3.11 wheels here, which is no longer needed.
> Stop building Python 3.11 wheels

- requirements.txt
We have a small local catastrophe in one of custom components. 3.12 upgrade left us without per-compiled wheel for `marisa-trie`.
https://github.com/DurgNomis-drol/ha_toyota/issues/258
I did fix that with cross-system QEMU build for `aarch64`, but `armv?l` is not supported by that.
https://github.com/pytries/marisa-trie/pull/101
https://github.com/pytries/marisa-trie/pull/102
https://github.com/piwheels/piwheels/issues/346
Maybe this is the correct place to provide a wheel for 32-bit Raspberries?
> feat: add marisa-trie

- builder/__main__.py
- builder/infra.py
- requirements.txt
- tests/test_infra.py
Noticed that some wheels are always build and uploaded even though the current version already exists on https://wheels.home-assistant.io/musllinux/. Notably `charset-normalizer` and `pymicro-vad`. The reason for it is that the package name in the constraints file doesn't match the wheel name spelling => `-` vs `_`.
```
charset-normalizer==3.4.0
pymicro-vad==1.0.1
charset_normalizer-3.4.0-py3-none-any.whl
pymicro_vad-1.0.1-cp312-cp312-musllinux_1_2_x86_64.whl
```
This PR uses `packaging` to normalize the package names and prevent duplicate wheel builds and uploads.
https://github.com/home-assistant/core/actions/runs/11683262865/job/32532124722#step:12:2598
> Normalize package names

- README.md
- requirements_cp312.txt
Core was updated to use the latest numpy release `2.1.2`.
https://github.com/home-assistant/core/pull/129958
> Update numpy to 2.1.2

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- README.md
- requirements_cp313.txt
Waiting on a new release of `docker-base` with Python 3.13. https://github.com/home-assistant/docker-base
> Add support for Python 3.13

- builder/infra.py
- tests/test_infra.py
Fix a small issue introduced with #794.
Without this PR, the code would raise a `KeyError`.
```py
...
for binary in exists:
version = binary_package_map[binary]
print(f"Found existing wheels for {binary}, removing local copy {version}")
>           for wheel in wheel_map[binary]:
E           KeyError: 'grpcio'
```
> Fix remove_local_wheels for no build wheels

- requirements_cp312.txt
- requirements_cp313.txt
Core was updated to `2.1.3` today: https://github.com/home-assistant/core/pull/130191.
> Update numpy to 2.1.3

- .github/workflows/ci.yml
`grpcio` is not part of the test wheel build.
https://github.com/home-assistant/wheels/blob/837cf9f7edb4a1136dff1db618b152cc4e4b5bc9/requirements_wheels_test.txt#L1-L6
> Remove grpc environment variables

- 0001-Support-musllinux-armv6l.patch
- Dockerfile
https://github.com/pypa/auditwheel/blob/6.1.0/CHANGELOG.md
> Update auditwheel to 6.1.0

- action.yml
We setup multiarch by default currently. Typically GitHub Action runners are x86_64 machines. `multiarch/qemu-user-static` only supports `linux/amd64`. For some existing target architectures QEMU is not even needed (amd64 and i386 to be specific).
Also, this prevents using `aarch64` builder. Since currently `multiarch/qemu-user-static` does not support `aarch64` host machines, simply skip setup in that case.
> Add check if QEMU is actually required to build wheels

- builder/wheel.py
- tests/conftest.py
- tests/test_wheel.py
Minor musl versions are backwards compatible. E.g. if a package builds its binaries for `musllinux_1_1`, they can still be installed on `musllinux_1_2` or newer. This can be seen when checking the output of `pip debug` as well.
```bash
docker run -it --rm ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21 bash
pip debug
```
```py
Compatible tags: 132
cp313-cp313-musllinux_1_2_aarch64
cp313-cp313-musllinux_1_1_aarch64
cp313-cp313-musllinux_1_0_aarch64
...
```
By updating the platform check logic, we can prevent unnecessary builds and reuse more (potentially) existing wheels from PyPI.
--
This would have prevented an issue a few days ago where the wheel builder was for some reason (probably insufficient memory) unable to build `awscrt-0.24.1-cp313-abi3-musllinux_1_2_aarch64`, even …
> Support wheels builds with older musl versions

- README.md
- requirements_cp313.txt
https://github.com/numpy/numpy/releases/tag/v2.3.0
Related core PR:
- https://github.com/home-assistant/core/pull/146296
> Update numpy to 2.3.0
