home-assistant/wheels

builder/pip.py, requirements_tests.txt, tests/__init__.py, tests/requirements/constraints.txt, tests/requirements/requirements.txt, tests/requirements/requirements_all.txt, tests/test_pip.py, tox.ini
Add support for `-c` and `-r` in requirements files.
=> Support more requirements things

Dockerfile
Signed-off-by: Pascal Vizeli <pvizeli@syshack.ch>
=> patchelf from source

action.yml
Fixes https://github.com/home-assistant/wheels-custom-integrations/pull/237/checks?check_run_id=1679385621
=> Ignore SSH if test

builder/__main__.py
```
File "/usr/local/lib/python3.10/site-packages/builder/__main__.py", line 191, in builder
for package, version in package_wrong.items():
AttributeError: 'bool' object has no attribute 'items'
```
=> Fix walnus issue

action.yml
Fix deprecated command `set-output` in action.yml
Missed it last time.
=> Fix deprecated command `set-output` in action.yml

.github/workflows/ci.yml, .github/workflows/publish.yml, README.md, requirements_cp311.txt
Adds builder for the cp311 ABI for Python 3.11
=> Add Python cp311 abi

builder/wheel.py
Fixes: https://github.com/home-assistant/wheels/actions/runs/4757647592/jobs/8455519659
=> Add support for Alpine 3.17 to wheel builder

action.yml
=> Remove CAS from action

.github/workflows/publish.yml
Found another place that needed cleanup
=> Remove CAS from publish workflow

.github/workflows/publish.yml
=> Update base image to Alpine 3.18

builder/wheel.py
Fixes:
https://github.com/home-assistant/core/actions/runs/6435311230/job/17476300103
=> Add Alpine 3.18 platform to Wheel builder

action.yml, builder/__main__.py, builder/pip.py
Cleans up the Legacy resolver. We have switched to use the new resolver a few months ago. This is thus now unused.
../Frenck
=> Clean up legacy resolver from Wheels builder

.github/workflows/publish.yml, README.md
=> Update to Alpine Linux 3.19

README.md, requirements_cp312.txt
SSIA
Also adjusted a wrong listed Cythonv version
=> Bump numpy to 1.26.3 in cp312

.devcontainer/Dockerfile, .github/workflows/ci.yml
=> Update devcontainer/CI to Python 3.12

requirements.txt
Reverts home-assistant/wheels#711
@vermut So sorry about this, but I've must have been sleeping. 
This PR was added to the wrong repository, it should be added to this repository instead:
<https://github.com/home-assistant/wheels-custom-integrations>
The good news is though, the CI passes and we can build the wheels 👍 
../Frenck
=> Revert "feat: add marisa-trie"

.github/workflows/publish.yml, README.md
=> Bump Alpine Linux to 3.20

builder/wheel.py
Ref: https://github.com/home-assistant/core/actions/runs/9845625903/job/27181564081
=> Add Alpine 3.20 platform to the Wheels builder

requirements.txt
https://github.com/pypa/packaging/releases/tag/24.2
=> Update packaging to 24.2

README.md, requirements_cp312.txt, requirements_cp313.txt
https://github.com/numpy/numpy/releases/tag/v2.2.0
Wheels are up on https://wheels.home-assistant.io/musllinux/
=> Update numpy to 2.2.0

.github/workflows/publish.yml, README.md, builder/wheel.py
https://github.com/home-assistant/docker-base/releases/tag/2024.12.0
https://github.com/home-assistant/docker-base/releases/tag/2024.12.1
=> Update docker base image to alpine3.21

README.md, requirements_cp312.txt, requirements_cp313.txt
https://github.com/numpy/numpy/releases/tag/v2.2.1
Wheels are up on https://wheels.home-assistant.io/musllinux/
=> Update numpy to 2.2.1

README.md, requirements_cp312.txt, requirements_cp313.txt
https://github.com/numpy/numpy/releases/tag/v2.2.2
Wheels are up on https://wheels.home-assistant.io/musllinux/
=> Update numpy to 2.2.2

README.md, requirements_cp313.txt
https://github.com/cython/cython/releases/tag/3.0.12
Only updated 3.13 to not conflict with #833.
=> Update cython to 3.0.12
